# Generated by Django 3.2.18 on 2023-03-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFK', '0002_alter_studentmodel_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=70)),
                ('Category_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Brand', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('MFD', models.DateField(auto_now_add=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppFK.categorymodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseModel',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
